package by.system.gethired.enums;

public enum UserState {
    IDLE,
    WAITING_FOR_JOB_TITLE,
    WAITING_FOR_LOCATION,
    WAITING_FOR_SALARY_RANGE,
    WAITING_FOR_INCLUDE_KEYWORDS,
    WAITING_FOR_EXCLUDE_KEYWORDS,
    WAITING_FOR_RESUME_FILE,
    WAITING_FOR_COVER_LETTER_FILE,
    WAITING_FOR_VACANCY_ID_FOR_GENERATION
}