spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.3
      embedding:
        enabled: false

    ollama:
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text
      chat:
        model: llama3

    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}